# Generated by Django 5.0.4 on 2024-05-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupjoinedrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'New'), (2, 'Rejected')]),
        ),
    ]
